Global:
  model_dir: ./ppyoloe_plus_crn_s_80e_coco
  format: paddle
  model_filename: model.pdmodel
  params_filename: model.pdiparams
  qat_image_path: ./COCO_train_320
  ptq_image_path: ./COCO_val_320
  input_list: ['image','scale_factor']
  qat_preprocess: ppyoloe_plus_withNMS_image_preprocess
  ptq_preprocess: ppyoloe_plus_withNMS_image_preprocess
  qat_batch_size: 4

Distillation:
  alpha: 1.0
  loss: soft_label

QuantAware:
  onnx_format: true
  use_pact: true
  activation_quantize_type: 'moving_average_abs_max'
  quantize_op_types:
  - conv2d
  - depthwise_conv2d


PTQ:
  calibration_method: 'avg'   # option: avg, abs_max, hist, KL, mse
  skip_tensor_list: None

TrainConfig:
  train_iter: 5000
  learning_rate:
    type: CosineAnnealingDecay
    learning_rate: 0.00003
    T_max: 6000
  optimizer_builder:
    optimizer:
      type: SGD
    weight_decay: 4.0e-05
