Global:
  model_dir: ./FCN_HRNet_W18_cityscapes_without_argmax_infer
  format: paddle
  model_filename: model.pdmodel
  params_filename: model.pdiparams
  qat_image_path: ./train_stuttgart
  ptq_image_path: ./train_stuttgart
  input_list: ['x']
  qat_preprocess: ppseg_cityscapes_qat_preprocess
  ptq_preprocess: ppseg_cityscapes_ptq_preprocess
  qat_batch_size: 2

Distillation:
  alpha: 1.0
  loss: l2
  node:
  - conv2d_613.tmp_1

QuantAware:
  onnx_format: True
  quantize_op_types:
  - conv2d
  - depthwise_conv2d

TrainConfig:
  epochs: 20
  eval_iter: 360
  learning_rate: 0.0001
  optimizer_builder:
    optimizer:
      type: SGD
    weight_decay: 4.0e-05

PTQ:
  calibration_method: 'avg'   # option: avg, abs_max, hist, KL, mse
  skip_tensor_list: None
